### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by caspervanneck** [Sandertv/EssentialsPE#2]
30.10 23:51:26 [Server] INFO Notice: Undefined offset: 364 in phar:///plugins/phar_EssentialsPE-patch-1_FkSN_Jav1kzrjJt.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 514
30.10 23:51:26 [Server] INFO Notice: Undefined offset: 364 in phar:///plugins/phar_EssentialsPE-patch-1_FkSN_Jav1kzrjJt.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 512

**Comment by Sandertv** [comment]
Okay, thanks for reporting! Is this that error that keeps showing up over and over again on console?

**Comment by Sandertv** [comment]
Fixed it in latest commit, it it doesn't work just shoot me a message :)

**Comment by caspervanneck** [comment]
@Sandertv  it dont work


31.10 01:00:19 [Server] INFO Notice: Undefined offset: 13 in /plugins/EssentialsPE-patch-1/src/EssentialsPE/BaseFiles/BaseSession.php on line 512
31.10 01:00:19 [Server] INFO Notice: Undefined offset: 13 in /plugins/EssentialsPE-patch-1/src/EssentialsPE/BaseFiles/BaseSession.php on line 512

**Comment by Sandertv** [comment]
Hmmm...

**Comment by Sandertv** [comment]
Okay I made another small change, would you please check if this does the job?

**Comment by Sandertv** [comment]
Any results?

**Comment by caspervanneck** [comment]
@Sandertv  y dont us it clearsky dont work with it

**Comment by Sandertv** [comment]
I'll try it another time, do you know when this error occures?

**Comment by Sandertv** [comment]
Okay try the new version, it might fix it.

**Comment by caspervanneck** [comment]
@Sandertv  can you fix that it works for clearsky

**Comment by caspervanneck** [comment]
i cant join my server if EssentialsPE  is eneblet

**Comment by Sandertv** [comment]
You can't?? What does it say?

**Comment by caspervanneck** [comment]
nothing XD @Sandertv

**Comment by Sandertv** [comment]
Do you crash when joining? Is the plugin disabling?

**Comment by caspervanneck** [comment]
no uhm i disconeck

**Comment by caspervanneck** [comment]
@Sandertv

**Comment by caspervanneck** [comment]
but i swhits to alywing or somting callt

**Comment by caspervanneck** [comment]
its fix thank you @Sandertv the eror

**Comment by Sandertv** [comment]
It's fixed? Okay awesome!
