### ISSUE TITLE
Broken perms

### ISSUE THREAD

**Issue by Tolo0** [Sandertv/EssentialsPE#4]
Some of the perms dont seem to be working. only op has perm to use the commands of

Fly
Repair 
Back
Heal

and maybe some others.

**Comment by Sandertv** [comment]
I'll look into it, thanks for reporting.

**Comment by Sandertv** [comment]
Just to confirm, did you use (for example) the permission 'essentials.fly.use' for players to be able to use the /fly command? The permission 'essentials.fly' may or may not work.

**Comment by Tolo0** [comment]
yep i used perms
- essentials.fly
- essentials.fly.use

just to be sure lol

**Comment by Sandertv** [comment]
You could try giving the permission essentials.fly.other too, it might work. (Just give it a try ;))

**Comment by Tolo0** [comment]
hey sorry to waist your time. I discovered the problem. i was using a old version of pureperms lol. iv updated it now. and all works fine.

**Comment by Sandertv** [comment]
Ah great! That's fixed then! No problem at all.
