### ISSUE TITLE
/fix or /repair

### ISSUE THREAD

**Issue by SuperDude36** [Sandertv/EssentialsPE#5]
It says I have fixed the item but it doesn't and says this in console: Notice: Undefined offset: 0 in /Users/superserver/ServerReset/plugins/EssentialsPE-patch-1/src/EssentialsPE/Commands/Repair.php on line 33

**Comment by Sandertv** [comment]
Cool! Thanks for reporting the bug, I'm looking into it!

**Comment by Sandertv** [comment]
Feel free to move back to the old repository now by the way, the commits got merged and I got write access, so I'm going to shut this down again soon.

**Comment by Sandertv** [comment]
I've noticed there's a visual bug where it LOOKS like item isn't repaired, but when you hit the ground with it it should act like it should again. The error I'll quickly fix in the main reposiotyr

**Comment by Sandertv** [comment]
I've fixed it here:
https://github.com/LegendOfMCPE/EssentialsPE
