### ISSUE TITLE
/fly command bug

### ISSUE THREAD

**Issue by SuperAlecs** [Sandertv/EssentialsPE#6]
When player flying and it run /fly the fly doesn't remove it stay on air.

**Comment by Sandertv** [comment]
I can't reproduce this. What server software do you use?

**Comment by SuperAlecs** [comment]
i use genisys

**Comment by Sandertv** [comment]
What happens when you use the command when you're flying? Does the console show an error?

**Comment by SuperAlecs** [comment]
I still flying, the console don't say anithing

**Comment by SuperAlecs** [comment]
I use windows 10 i don't know what happens with pocket edition

**Comment by Sandertv** [comment]
That might in fact be the problem!! It works alright in PE version.

**Comment by Sandertv** [comment]
I'm sorry to say I have no control over this, this is a server software issue. Try to submit it there.

**Comment by SuperAlecs** [comment]
@dktapps told me this is 0.15 client bug but now i have 0.16 and the bug is still

**Comment by Sandertv** [comment]
I'm guessing that client bug still didn't get fixed yet... I really don't have any control over it and i think neither does dktapps.

**Comment by SuperAlecs** [comment]
Okok sorry for useless issue

**Comment by Sandertv** [comment]
No problem, sorry I can't help with this.
